/**
 * Artifact Generator - Produces final injectable artifacts from mode outputs
 */

import type { 
  Layer1Output, 
  Layer2Output, 
  Layer3Output 
} from '../modes/planning/index.js';
import type { 
  Layer1AssumptionOutput,
  Layer2ActionOutput,
  Layer3ObservationOutput,
  Layer4GapAnalysisOutput,
  Layer5MetaReflectionOutput,
  Layer6VerificationOutput
} from '../modes/problem-solving/index.js';

export interface ArtifactResult {
  filename: string;
  content: string;
  tokenCount: number;
  injectable: boolean;
}

export class ArtifactGenerator {
  generatePlanningContextLibrary(outputs: {
    layer1: Layer1Output | null;
    layer2: Layer2Output | null;
    layer3: Layer3Output | null;
  }): ArtifactResult {
    
    const content = `# CONTEXT LIBRARY: ${outputs.layer1?.surfaceUnderstanding || 'Project'}

## Architecture Overview
${outputs.layer3?.architecture || 'Architecture pending'}

---

## Surface Understanding
${outputs.layer1?.surfaceUnderstanding || ''}

---

## First Principles
${outputs.layer1?.firstPrinciples?.map((p: string, i: number) => `${i + 1}. ${p}`).join('\n') || ''}

---

## Components
${outputs.layer2?.components?.map((c: string) => `- ${c}`).join('\n') || ''}

---

## Dependencies
${outputs.layer2?.dependencies?.map((d: string) => `- ${d}`).join('\n') || ''}

---

## Interfaces
${outputs.layer3?.interfaces || ''}

---

## State Management
${outputs.layer3?.stateManagement || ''}

---

## Success Criteria
${outputs.layer1?.successCriteria?.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n') || ''}

---

## Failure Modes
${outputs.layer2?.failureModes?.map((f: string) => `- ${f}`).join('\n') || ''}

---

*Generated by Trident Brain - Deep Planning Mode*
*DO NOT EDIT - Injectable artifact*`;

    return {
      filename: 'CONTEXT_LIBRARY.md',
      content,
      tokenCount: this.estimateTokens(content),
      injectable: true
    };
  }

  generateProblemSolvingChain(outputs: {
    layer1: Layer1AssumptionOutput | null;
    layer2: Layer2ActionOutput | null;
    layer3: Layer3ObservationOutput | null;
    layer4: Layer4GapAnalysisOutput | null;
    layer5: Layer5MetaReflectionOutput | null;
    layer6: Layer6VerificationOutput | null;
  }, iteration: string): ArtifactResult {
    
    const content = `# PROBLEM SOLVING CHAIN — Iteration ${iteration}

## Problem Statement
${outputs.layer1?.problemStatement || ''}

---

## 1. Assumption
**Assumption:** ${outputs.layer1?.explicitAssumption || ''}

**Reasoning Chain:**
${outputs.layer1?.reasoningChain?.map((r: string, i: number) => `${i + 1}. ${r}`).join('\n') || ''}

**Success Criteria:**
${outputs.layer1?.successCriteria?.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n') || ''}

---

## 2. Action
**Command:** \`\`\`${outputs.layer2?.exactCommand || ''}\`\`\`

**Expected Output:** \`\`\`${outputs.layer2?.expectedOutput || ''}\`\`\`

**Environment State:** ${JSON.stringify(outputs.layer2?.environmentState || {})}

---

## 3. Observation
**Raw Evidence:**
\`\`\`
${outputs.layer3?.rawEvidence || ''}
\`\`\`

**Expected vs Actual:**
| Aspect | Expected | Actual | Gap |
|--------|----------|---------|-----|
${outputs.layer3?.expectedVsActual?.map((e: any) => `| ${e.aspect} | ${e.expected} | ${e.actual} | ${e.difference} |`).join('\n') || ''}

---

## 4. Gap Analysis
**Updated Hypothesis:** ${outputs.layer4?.updatedHypothesis || ''}

**Next Action:** ${outputs.layer4?.nextAction || ''}

**Iteration History:**
${outputs.layer4?.iterationHistory?.map((i: any) => `- ${i.iteration}: ${i.updatedHypothesis}`).join('\n') || ''}

---

## 5. Meta-Reflection
**What I Should Have Done:**
${outputs.layer5?.whatIShouldHaveDone?.map((w: any) => `- ${w.step}: ${w.whatIShouldHaveDone}`).join('\n') || ''}

**Pattern Extracted:** ${outputs.layer5?.patternExtracted?.name || ''} - ${outputs.layer5?.patternExtracted?.description || ''}

---

## 6. Verification
**Status:** ${outputs.layer6?.finalAssessment?.status || ''}
**Confidence:** ${outputs.layer6?.finalAssessment?.confidence || ''}

**Requirements Met:**
${outputs.layer6?.requirementsMet?.map((r: any) => `- ${r.requirement}: ${r.met ? '✅' : '❌'}`).join('\n') || ''}

---

*Generated by Trident Brain - Problem Solving Mode*
*DO NOT EDIT - Injectable artifact*`;

    return {
      filename: `PROBLEM_SOLVING_CHAIN_${iteration}.md`,
      content,
      tokenCount: this.estimateTokens(content),
      injectable: true
    };
  }

  generateModeIndex(mode: 'planning' | 'problem-solving' | 'context-synthesis'): ArtifactResult {
    const content = `# TRIDENT BRAIN MODE INDEX

## ${mode.toUpperCase()} MODE

### Available Layers

${this.getLayerIndex(mode)}

---

### Quick Reference

${this.getQuickReference(mode)}

---

*Generated by Trident Brain*
*DO NOT EDIT - Injectable artifact*`;

    return {
      filename: 'MODE_INDEX.md',
      content,
      tokenCount: this.estimateTokens(content),
      injectable: true
    };
  }

  private getLayerIndex(mode: string): string {
    switch (mode) {
      case 'planning':
        return `1. Layer 1: Initial Plan
2. Layer 2: Detailed Workflow
3. Layer 3: Context Library`;
      case 'problem-solving':
        return `1. Layer 1: Assumption Statement
2. Layer 2: Action with Prediction
3. Layer 3: Observation & Evidence
4. Layer 4: Gap Analysis & Adjustment
5. Layer 5: Meta-Cognitive Reflection
6. Layer 6: Verification & Confirmation`;
      case 'context-synthesis':
        return `1. Layer 1: Context Collection
2. Layer 2: Relevance Scoring
3. Layer 3: Compression
4. Layer 4: Injection Format`;
      default:
        return '';
    }
  }

  private getQuickReference(mode: string): string {
    switch (mode) {
      case 'planning':
        return `- Thinking: "What is this really?"
- Thinking: "How does it decompose?"
- Thinking: "Can I explain to another agent?"`;
      case 'problem-solving':
        return `- Thinking: "What do I assume?"
- Thinking: "What action + expected?"
- Thinking: "What actually happened?"
- Thinking: "What does the gap tell me?"
- Thinking: "What should I have done differently?"
- Thinking: "How do I confirm fix works?"`;
      case 'context-synthesis':
        return `- Thinking: "What context exists?"
- Thinking: "What matters most?"
- Thinking: "How to compress?"
- Thinking: "How to inject?"`;
      default:
        return '';
    }
  }

  private estimateTokens(text: string): number {
    return Math.ceil(text.length / 4);
  }
}

export default new ArtifactGenerator();